### ISSUE TITLE
Move code to Agent repository

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-annotations#19]
Since we've open sourced the agent where the annotations are used we should just move code from this repository to the agent one: https://github.com/cirruslabs/cirrus-ci-agent. So there is no need for an additional release in the agent repo.

**Comment by edigaryev** [comment]
>we should just move code from this repository to the agent one

Any idea what to do with the MIT and the MPL-2.0 mismatch though?

Should we just put the [LICENSE](https://github.com/cirruslabs/cirrus-ci-annotations/blob/master/LICENSE) contents in all of the transferred files? Perhaps substantial contributors should be included in the copyright notice too, similarly to e.g. [OpenSSH](https://github.com/openbsd/src/blob/master/usr.bin/ssh/scp.c)?

**Comment by fkorotkov** [comment]
On a second though it might be easier to leave it as is but just start doing proper releases. It will be easier in the future to navigate users to this repository in order to add support for formats they want. And also to your point it will be easier for others to integrate this library once we have **a lot** of formats.

**Comment by edigaryev** [comment]
So, I'm closing this as it seems that we're doing it now, but here's a nice example of how this can be done in the future: https://github.com/image-rs/image/issues/503
