### ISSUE TITLE
Support "go test -json" ouput

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-annotations#23]
`go test -json ./...` can produce a nice stream of json events for tests that can be converted to annotations. The only caveat is that it doesn't seem possible to have both json output to a file and a normal output to console at the same time: one for realtime log streaming and the other for generating annotations.

FYI @edigaryev

**Comment by fkorotkov** [comment]
Getting both the outputs is possible via [gotestsum](https://github.com/gotestyourself/gotestsum)! We should either support their JUnit format or get the raw JSON events and create annotations from them.

**Comment by edigaryev** [comment]
It seems that neither of these solutions produce file names and line numbers needed to create the [GitHub Annotation](https://developer.github.com/v3/checks/runs/#annotations-object) object.

I've looked into https://github.com/jstemmer/go-junit-report and it also somewhat misses the point of generating machine-readable test results:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="10" failures="1" time="0.061" name="github.com/cirruslabs/cirrus-ci-annotations/parsers">
		<properties>
			<property name="go.version" value="go1.15"></property>
		</properties>
		<testcase classname="parsers" name="Test_AndroidLint_Multiple_Locations" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_AndroidLint_Multiple_Issues" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_AndroidLint_Ignored_Issue" time="0.000"></testcase>
		<testcase classname="parsers" name="TestDummy" time="0.000">
			<failure message="Failed" type="">    dummy_test.go:6: keks&#xA;    dummy_test.go:7: designed to fail</failure>
		</testcase>
		<testcase classname="parsers" name="Test_GoLangCI" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_JunitJava" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_JunitKotlin" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_PythonXMLRunner" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_RSpec_MultipleStates" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_RuboCop_DocsExample" time="0.000"></testcase>
	</testsuite>
</testsuites>
```

Perhaps my assumption is wrong and you can still generate annotations with this? Or we need to dig deeper and parse the actual test output (perhaps as a part of [gotestsum's](https://github.com/gotestyourself/gotestsum) codebase)?

**Comment by edigaryev** [comment]
It seems that neither of these solutions produce file names and line numbers needed to create the [GitHub Annotation](https://developer.github.com/v3/checks/runs/#annotations-object) object.

I've looked into https://github.com/jstemmer/go-junit-report and it also somewhat misses the point of generating machine-readable test results:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="10" failures="1" time="0.061" name="github.com/cirruslabs/cirrus-ci-annotations/parsers">
		<properties>
			<property name="go.version" value="go1.15"></property>
		</properties>
		<testcase classname="parsers" name="Test_AndroidLint_Multiple_Locations" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_AndroidLint_Multiple_Issues" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_AndroidLint_Ignored_Issue" time="0.000"></testcase>
		<testcase classname="parsers" name="TestDummy" time="0.000">
			<failure message="Failed" type="">    dummy_test.go:6: this test&#xA;    dummy_test.go:7: is designed to fail</failure>
		</testcase>
		<testcase classname="parsers" name="Test_GoLangCI" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_JunitJava" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_JunitKotlin" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_PythonXMLRunner" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_RSpec_MultipleStates" time="0.000"></testcase>
		<testcase classname="parsers" name="Test_RuboCop_DocsExample" time="0.000"></testcase>
	</testsuite>
</testsuites>
```

Perhaps my assumption is wrong and you can still generate annotations with this? Or we need to dig deeper and parse the actual test output (perhaps as a part of [gotestsum's](https://github.com/gotestyourself/gotestsum) codebase)?

**Comment by fkorotkov** [comment]
Doesn't seem it's there 😪 https://golang.org/cmd/test2json/#hdr-Output_Format

Quite ridiculous 😲
